# Generated by Django 3.2.19 on 2023-05-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saboreaSoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('correo', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('usuario_credencial', models.CharField(max_length=30, unique=True)),
                ('contrasenia_credencial', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'credencial',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'descuento',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_prod', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='static/uploads')),
                ('categoria', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saboreaSoft.descuento')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'restaurante',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saboreaSoft.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saboreaSoft.producto')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_identificacion', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tipo_documento', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=30, null=True)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saboreaSoft.credencial')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='nit_restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saboreaSoft.restaurante'),
        ),
    ]
